version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: hospital_db
    ports:
      - "7878:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db